conform to new cli spec

diff --git a/ldap/shell/getphone b/ldap/shell/getphone
--- a/ldap/shell/getphone
+++ b/ldap/shell/getphone
@@ -2,75 +2,54 @@
 # Utility functions for accessing AD from the shell. Requires the OpenLDAP
 # command-line tools (ldapsearch, etc.)
 
-# Get the LDAP URL from the environment, or default to known value
-: "${AD_LDAP_URL:=ldap://ldap.turner.com}"
-
 # Demonstration code
 main() {
-  local dn tel
-  if (( $# < 1 )); then
-    echo >&2 "Usage: $0 username"
-    return 1
-  fi
-  IFS=$'\n' read -d '' dn tel <<<"$(ad_ldap search -b cn=users,dc=turner,dc=com \
-                   "samaccountname=$1" telephoneNumber |
-                   sed -n 's/^\(dn\|telephoneNumber\): //p')"
-  printf "DN: %s\nPhone: %s\n" "$dn" "$tel"
+
+  # need username to look up
+  (( $# != 1 )) && die "Usage: $0 username"
+
+   # Get the LDAP URL from the environment, or default to known value
+   : "${AD_LDAP_URL:=ldap://ldap.turner.com}"
+
+   # No defaults for credentials
+   [[ -z $AD_LDAP_BIND_DN       ]] && die "$0: AD_LDAP_BIND_DN must be set."
+   [[ -z $AD_LDAP_BIND_PASSWORD ]] && die "$0: AD_LDAP_BIND_PASSWORD must be set."
+
+   ad_ldap search -b cn=users,dc=turner,dc=com "samaccountname=$1" telephonenumber |
+     sed -n 's/^telephoneNumber: //p'
+}
+
+die() {
+  printf >&2 '%s\n' "$*"
+  exit 1
 }
 
 ad_ldap () {
-  # generic front-end function; first argument is the name of the command to run,
+  # generic front-end helper function; first argument is the name of the command to run,
   # minus the 'ldap' part. Requires credentials to be set in environment variables.
-  local cmd=ldap$1
+  local exe=ldap$1
   shift
 
-  type -P "$cmd" >/dev/null || {
-    printf >&2 "%s: %s: command not found" "$0" "$cmd"
+  type -P "$exe" >/dev/null || {
+    printf >&2 "%s: %s: command not found" "$0" "$exe"
     return 1
   }
 
-  # make sure credentials are set
-  ad_check_credentials || return 1
+  # building up the command as an array is just so I can add comments to each
+  # component
+  local cmd=("$exe" 
+    -H "$AD_LDAP_URL"               # URL to connect to
+    -ZZ                             # make TLS negotiation mandatory
+    -x                              # use basic user/pass auth for bind
+    -D "$AD_LDAP_BIND_DN"           # bind as this user
+    -w "$AD_LDAP_BIND_PASSWORD"     # with this password
+    "$@")                            # add rest of the arguments
 
-  # this allows OpenLDAP-based commands to use SSL or TLS for encryption
-  # without requiring that they be able to validate the server certificate
-  export LDAPTLS_REQCERT=never
-
-  "$cmd" -H "$AD_LDAP_URL" -ZZ \
-     -x -D "$AD_LDAP_BIND_DN" -w "$AD_LDAP_BIND_PASSWORD" "$@"
-}
-
-# Make sure credentials are set
-ad_check_credentials()
-{
-  [[ -n $AD_LDAP_BIND_DN && -n $AD_LDAP_BIND_PASSWORD ]] && return 0
-
-  # not set.  If we're not being run interactively, fail
-  if [[ ! -t 0 ]]; then
-    printf >&2 "%s: no credentials supplied" "$0"
-    return 1
-  fi
-
-  # Otherwise, prompt
-  ad_get_credentials
-}
-
-# Get credentials for bind
-ad_get_credentials() {
-  local bind_user old_stty
-  read -p 'Enter LDAP Username: ' bind_user >/dev/tty
-  if [[ $bind_user =~ ^[^\\,]*$ ]]; then # simple username
-    AD_LDAP_BIND_DN=Turner\\$bind_user
-  else
-    AD_LDAP_BIND_DN=$bind_user
-  fi
-
-  # turn off echo to read password
-  old_stty="$(stty -f /dev/tty -a | grep -ow -e '-\?echo')"
-  stty -f /dev/tty -echo
-  read -p 'Enter LDAP Password: ' AD_LDAP_BIND_PASSWORD >/dev/tty
-  stty -f /dev/tty "$old_stty"
-  printf $'\n' >/dev/tty
+  # The LDAPTLS_REQCERT envar allows OpenLDAP-based commands to use SSL or TLS
+  # for encryption without requiring that they be able to validate the server
+  # certificate. Putting it on the command line means we just set it for the
+  # duration of that one command.
+  LDAPTLS_REQCERT=never "${cmd[@]}"
 }
 
 main "$@"
